apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "letsencrypt-staging"
spec:
  acme:
    email: alexanderdolgosheev@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: kube-practice-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx 